// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // CourseOffering
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class CourseOfferingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CourseOffering>
    {
        public CourseOfferingConfiguration()
            : this("edfi")
        {
        }

        public CourseOfferingConfiguration(string schema)
        {
            ToTable("CourseOffering", schema);
            HasKey(x => new { x.LocalCourseCode, x.SchoolId, x.SchoolYear, x.SessionName });

            Property(x => x.LocalCourseCode).HasColumnName(@"LocalCourseCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(60).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SchoolId).HasColumnName(@"SchoolId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SchoolYear).HasColumnName(@"SchoolYear").HasColumnType("smallint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SessionName).HasColumnName(@"SessionName").HasColumnType("nvarchar").IsRequired().HasMaxLength(60).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.LocalCourseTitle).HasColumnName(@"LocalCourseTitle").HasColumnType("nvarchar").IsOptional().HasMaxLength(60);
            Property(x => x.InstructionalTimePlanned).HasColumnName(@"InstructionalTimePlanned").HasColumnType("int").IsOptional();
            Property(x => x.CourseCode).HasColumnName(@"CourseCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(60);
            Property(x => x.EducationOrganizationId).HasColumnName(@"EducationOrganizationId").HasColumnType("int").IsRequired();
            Property(x => x.Discriminator).HasColumnName(@"Discriminator").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.LastModifiedDate).HasColumnName(@"LastModifiedDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.ChangeVersion).HasColumnName(@"ChangeVersion").HasColumnType("bigint").IsRequired();

            // Foreign keys
            HasRequired(a => a.School).WithMany(b => b.CourseOfferings).HasForeignKey(c => c.SchoolId).WillCascadeOnDelete(false); // FK_CourseOffering_School
            HasRequired(a => a.Session).WithMany(b => b.CourseOfferings).HasForeignKey(c => new { c.SchoolId, c.SchoolYear, c.SessionName }).WillCascadeOnDelete(false); // FK_CourseOffering_Session
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
