// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // ElectronicMailTypeDescriptor
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class ElectronicMailTypeDescriptorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ElectronicMailTypeDescriptor>
    {
        public ElectronicMailTypeDescriptorConfiguration()
            : this("edfi")
        {
        }

        public ElectronicMailTypeDescriptorConfiguration(string schema)
        {
            ToTable("ElectronicMailTypeDescriptor", schema);
            HasKey(x => x.ElectronicMailTypeDescriptorId);

            Property(x => x.ElectronicMailTypeDescriptorId).HasColumnName(@"ElectronicMailTypeDescriptorId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Descriptor).WithOptional(b => b.ElectronicMailTypeDescriptor); // FK_ElectronicMailTypeDescriptor_Descriptor
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
