// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // ElectronicMailTypeDescriptor
    ///<summary>
    /// The type of email listed for an individual or organization.
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class ElectronicMailTypeDescriptor
    {

        ///<summary>
        /// A unique identifier used as Primary Key, not derived from business logic, when acting as Foreign Key, references the parent table.
        ///</summary>
        public int ElectronicMailTypeDescriptorId { get; set; } // ElectronicMailTypeDescriptorId (Primary key)

        // Reverse navigation

        /// <summary>
        /// Child StaffElectronicMails where [StaffElectronicMail].[ElectronicMailTypeDescriptorId] point to this entity (FK_StaffElectronicMail_ElectronicMailTypeDescriptor)
        /// </summary>
        public System.Collections.Generic.ICollection<StaffElectronicMail> StaffElectronicMails { get; set; } // StaffElectronicMail.FK_StaffElectronicMail_ElectronicMailTypeDescriptor
        /// <summary>
        /// Child StudentEducationOrganizationAssociationElectronicMails where [StudentEducationOrganizationAssociationElectronicMail].[ElectronicMailTypeDescriptorId] point to this entity (FK_StudentEducationOrganizationAssociationElectronicMail_ElectronicMailTypeDescriptor)
        /// </summary>
        public System.Collections.Generic.ICollection<StudentEducationOrganizationAssociationElectronicMail> StudentEducationOrganizationAssociationElectronicMails { get; set; } // StudentEducationOrganizationAssociationElectronicMail.FK_StudentEducationOrganizationAssociationElectronicMail_ElectronicMailTypeDescriptor

        // Foreign keys

        /// <summary>
        /// Parent Descriptor pointed by [ElectronicMailTypeDescriptor].([ElectronicMailTypeDescriptorId]) (FK_ElectronicMailTypeDescriptor_Descriptor)
        /// </summary>
        public Descriptor Descriptor { get; set; } // FK_ElectronicMailTypeDescriptor_Descriptor

        public ElectronicMailTypeDescriptor()
        {
            StaffElectronicMails = new System.Collections.Generic.List<StaffElectronicMail>();
            StudentEducationOrganizationAssociationElectronicMails = new System.Collections.Generic.List<StudentEducationOrganizationAssociationElectronicMail>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
