// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // EntryGradeLevelReasonDescriptor
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class EntryGradeLevelReasonDescriptorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<EntryGradeLevelReasonDescriptor>
    {
        public EntryGradeLevelReasonDescriptorConfiguration()
            : this("edfi")
        {
        }

        public EntryGradeLevelReasonDescriptorConfiguration(string schema)
        {
            ToTable("EntryGradeLevelReasonDescriptor", schema);
            HasKey(x => x.EntryGradeLevelReasonDescriptorId);

            Property(x => x.EntryGradeLevelReasonDescriptorId).HasColumnName(@"EntryGradeLevelReasonDescriptorId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Descriptor).WithOptional(b => b.EntryGradeLevelReasonDescriptor); // FK_EntryGradeLevelReasonDescriptor_Descriptor
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
