// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // EntryGradeLevelReasonDescriptor
    ///<summary>
    /// The primary reason as to why a staff member determined that a student should be promoted or not (or be demoted) at the end of a given school term.
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class EntryGradeLevelReasonDescriptor
    {

        ///<summary>
        /// A unique identifier used as Primary Key, not derived from business logic, when acting as Foreign Key, references the parent table.
        ///</summary>
        public int EntryGradeLevelReasonDescriptorId { get; set; } // EntryGradeLevelReasonDescriptorId (Primary key)

        // Reverse navigation

        /// <summary>
        /// Child StudentSchoolAssociations where [StudentSchoolAssociation].[EntryGradeLevelReasonDescriptorId] point to this entity (FK_StudentSchoolAssociation_EntryGradeLevelReasonDescriptor)
        /// </summary>
        public System.Collections.Generic.ICollection<StudentSchoolAssociation> StudentSchoolAssociations { get; set; } // StudentSchoolAssociation.FK_StudentSchoolAssociation_EntryGradeLevelReasonDescriptor

        // Foreign keys

        /// <summary>
        /// Parent Descriptor pointed by [EntryGradeLevelReasonDescriptor].([EntryGradeLevelReasonDescriptorId]) (FK_EntryGradeLevelReasonDescriptor_Descriptor)
        /// </summary>
        public Descriptor Descriptor { get; set; } // FK_EntryGradeLevelReasonDescriptor_Descriptor

        public EntryGradeLevelReasonDescriptor()
        {
            StudentSchoolAssociations = new System.Collections.Generic.List<StudentSchoolAssociation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
