// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // GradeLevelDescriptor
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class GradeLevelDescriptorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<GradeLevelDescriptor>
    {
        public GradeLevelDescriptorConfiguration()
            : this("edfi")
        {
        }

        public GradeLevelDescriptorConfiguration(string schema)
        {
            ToTable("GradeLevelDescriptor", schema);
            HasKey(x => x.GradeLevelDescriptorId);

            Property(x => x.GradeLevelDescriptorId).HasColumnName(@"GradeLevelDescriptorId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Descriptor).WithOptional(b => b.GradeLevelDescriptor); // FK_GradeLevelDescriptor_Descriptor
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
