// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // GradeLevelDescriptor
    ///<summary>
    /// This descriptor defines the set of grade levels. The map to known Ed-Fi enumeration values is required.
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class GradeLevelDescriptor
    {

        ///<summary>
        /// A unique identifier used as Primary Key, not derived from business logic, when acting as Foreign Key, references the parent table.
        ///</summary>
        public int GradeLevelDescriptorId { get; set; } // GradeLevelDescriptorId (Primary key)

        // Reverse navigation

        /// <summary>
        /// Child SchoolGradeLevels where [SchoolGradeLevel].[GradeLevelDescriptorId] point to this entity (FK_SchoolGradeLevel_GradeLevelDescriptor)
        /// </summary>
        public System.Collections.Generic.ICollection<SchoolGradeLevel> SchoolGradeLevels { get; set; } // SchoolGradeLevel.FK_SchoolGradeLevel_GradeLevelDescriptor
        /// <summary>
        /// Child StudentSchoolAssociations where [StudentSchoolAssociation].[EntryGradeLevelDescriptorId] point to this entity (FK_StudentSchoolAssociation_GradeLevelDescriptor)
        /// </summary>
        public System.Collections.Generic.ICollection<StudentSchoolAssociation> StudentSchoolAssociations { get; set; } // StudentSchoolAssociation.FK_StudentSchoolAssociation_GradeLevelDescriptor

        // Foreign keys

        /// <summary>
        /// Parent Descriptor pointed by [GradeLevelDescriptor].([GradeLevelDescriptorId]) (FK_GradeLevelDescriptor_Descriptor)
        /// </summary>
        public Descriptor Descriptor { get; set; } // FK_GradeLevelDescriptor_Descriptor

        public GradeLevelDescriptor()
        {
            SchoolGradeLevels = new System.Collections.Generic.List<SchoolGradeLevel>();
            StudentSchoolAssociations = new System.Collections.Generic.List<StudentSchoolAssociation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
