// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    public partial interface IEdfiApiV3DbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<CourseOffering> CourseOfferings { get; set; } // CourseOffering
        System.Data.Entity.DbSet<Descriptor> Descriptors { get; set; } // Descriptor
        System.Data.Entity.DbSet<EducationOrganization> EducationOrganizations { get; set; } // EducationOrganization
        System.Data.Entity.DbSet<ElectronicMailTypeDescriptor> ElectronicMailTypeDescriptors { get; set; } // ElectronicMailTypeDescriptor
        System.Data.Entity.DbSet<EntryGradeLevelReasonDescriptor> EntryGradeLevelReasonDescriptors { get; set; } // EntryGradeLevelReasonDescriptor
        System.Data.Entity.DbSet<GradeLevelDescriptor> GradeLevelDescriptors { get; set; } // GradeLevelDescriptor
        System.Data.Entity.DbSet<LocalEducationAgency> LocalEducationAgencies { get; set; } // LocalEducationAgency
        System.Data.Entity.DbSet<Location> Locations { get; set; } // Location
        System.Data.Entity.DbSet<School> Schools { get; set; } // School
        System.Data.Entity.DbSet<SchoolCategory> SchoolCategories { get; set; } // SchoolCategory
        System.Data.Entity.DbSet<SchoolCategoryDescriptor> SchoolCategoryDescriptors { get; set; } // SchoolCategoryDescriptor
        System.Data.Entity.DbSet<SchoolGradeLevel> SchoolGradeLevels { get; set; } // SchoolGradeLevel
        System.Data.Entity.DbSet<Section> Sections { get; set; } // Section
        System.Data.Entity.DbSet<Session> Sessions { get; set; } // Session
        System.Data.Entity.DbSet<Staff> Staffs { get; set; } // Staff
        System.Data.Entity.DbSet<StaffElectronicMail> StaffElectronicMails { get; set; } // StaffElectronicMail
        System.Data.Entity.DbSet<StaffSectionAssociation> StaffSectionAssociations { get; set; } // StaffSectionAssociation
        System.Data.Entity.DbSet<Student> Students { get; set; } // Student
        System.Data.Entity.DbSet<StudentEducationOrganizationAssociation> StudentEducationOrganizationAssociations { get; set; } // StudentEducationOrganizationAssociation
        System.Data.Entity.DbSet<StudentEducationOrganizationAssociationElectronicMail> StudentEducationOrganizationAssociationElectronicMails { get; set; } // StudentEducationOrganizationAssociationElectronicMail
        System.Data.Entity.DbSet<StudentSchoolAssociation> StudentSchoolAssociations { get; set; } // StudentSchoolAssociation
        System.Data.Entity.DbSet<StudentSchoolAssociationEnrollmentType> StudentSchoolAssociationEnrollmentTypes { get; set; } // StudentSchoolAssociationEnrollmentType
        System.Data.Entity.DbSet<StudentSectionAssociation> StudentSectionAssociations { get; set; } // StudentSectionAssociation
        System.Data.Entity.DbSet<TermDescriptor> TermDescriptors { get; set; } // TermDescriptor

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
