// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // LocalEducationAgency
    ///<summary>
    /// This entity represents an administrative unit at the local level which exists primarily to operate schools or to contract for educational services. It includes school districts, charter schools, charter management organizations, or other local administrative organizations.
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class LocalEducationAgency
    {

        ///<summary>
        /// The identifier assigned to a local education agency.
        ///</summary>
        public int LocalEducationAgencyId { get; set; } // LocalEducationAgencyId (Primary key)

        ///<summary>
        /// The category of local education agency/district. For example: Independent or Charter.
        ///</summary>
        public int LocalEducationAgencyCategoryDescriptorId { get; set; } // LocalEducationAgencyCategoryDescriptorId

        ///<summary>
        /// A school or agency providing free public elementary or secondary education to eligible students under a specific charter granted by the state legislature or other appropriate authority and designated by such authority to be a charter school.
        ///</summary>
        public int? CharterStatusDescriptorId { get; set; } // CharterStatusDescriptorId

        ///<summary>
        /// The identifier assigned to a local education agency.
        ///</summary>
        public int? ParentLocalEducationAgencyId { get; set; } // ParentLocalEducationAgencyId

        ///<summary>
        /// The identifier assigned to an education service center.
        ///</summary>
        public int? EducationServiceCenterId { get; set; } // EducationServiceCenterId

        ///<summary>
        /// The identifier assigned to a state education agency.
        ///</summary>
        public int? StateEducationAgencyId { get; set; } // StateEducationAgencyId

        // Reverse navigation

        /// <summary>
        /// Child LocalEducationAgencies where [LocalEducationAgency].[ParentLocalEducationAgencyId] point to this entity (FK_LocalEducationAgency_LocalEducationAgency)
        /// </summary>
        public System.Collections.Generic.ICollection<LocalEducationAgency> LocalEducationAgencies { get; set; } // LocalEducationAgency.FK_LocalEducationAgency_LocalEducationAgency
        /// <summary>
        /// Child Schools where [School].[LocalEducationAgencyId] point to this entity (FK_School_LocalEducationAgency)
        /// </summary>
        public System.Collections.Generic.ICollection<School> Schools { get; set; } // School.FK_School_LocalEducationAgency

        // Foreign keys

        /// <summary>
        /// Parent EducationOrganization pointed by [LocalEducationAgency].([LocalEducationAgencyId]) (FK_LocalEducationAgency_EducationOrganization)
        /// </summary>
        public EducationOrganization EducationOrganization { get; set; } // FK_LocalEducationAgency_EducationOrganization

        /// <summary>
        /// Parent LocalEducationAgency pointed by [LocalEducationAgency].([ParentLocalEducationAgencyId]) (FK_LocalEducationAgency_LocalEducationAgency)
        /// </summary>
        public LocalEducationAgency ParentLocalEducationAgency { get; set; } // FK_LocalEducationAgency_LocalEducationAgency

        public LocalEducationAgency()
        {
            LocalEducationAgencies = new System.Collections.Generic.List<LocalEducationAgency>();
            Schools = new System.Collections.Generic.List<School>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
