// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // SchoolCategoryDescriptor
    ///<summary>
    /// The category of school. For example: High School, Middle School, Elementary School.
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class SchoolCategoryDescriptor
    {

        ///<summary>
        /// A unique identifier used as Primary Key, not derived from business logic, when acting as Foreign Key, references the parent table.
        ///</summary>
        public int SchoolCategoryDescriptorId { get; set; } // SchoolCategoryDescriptorId (Primary key)

        // Reverse navigation

        /// <summary>
        /// Child SchoolCategories where [SchoolCategory].[SchoolCategoryDescriptorId] point to this entity (FK_SchoolCategory_SchoolCategoryDescriptor)
        /// </summary>
        public System.Collections.Generic.ICollection<SchoolCategory> SchoolCategories { get; set; } // SchoolCategory.FK_SchoolCategory_SchoolCategoryDescriptor

        // Foreign keys

        /// <summary>
        /// Parent Descriptor pointed by [SchoolCategoryDescriptor].([SchoolCategoryDescriptorId]) (FK_SchoolCategoryDescriptor_Descriptor)
        /// </summary>
        public Descriptor Descriptor { get; set; } // FK_SchoolCategoryDescriptor_Descriptor

        public SchoolCategoryDescriptor()
        {
            SchoolCategories = new System.Collections.Generic.List<SchoolCategory>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
