// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // SchoolCategoryDescriptor
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class SchoolCategoryDescriptorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SchoolCategoryDescriptor>
    {
        public SchoolCategoryDescriptorConfiguration()
            : this("edfi")
        {
        }

        public SchoolCategoryDescriptorConfiguration(string schema)
        {
            ToTable("SchoolCategoryDescriptor", schema);
            HasKey(x => x.SchoolCategoryDescriptorId);

            Property(x => x.SchoolCategoryDescriptorId).HasColumnName(@"SchoolCategoryDescriptorId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Descriptor).WithOptional(b => b.SchoolCategoryDescriptor); // FK_SchoolCategoryDescriptor_Descriptor
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
