// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // SchoolCategory
    ///<summary>
    /// The one or more categories of school. For example: High School, Middle School, and/or Elementary School.
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class SchoolCategory
    {

        ///<summary>
        /// The one or more categories of school. For example: High School, Middle School, and/or Elementary School.
        ///</summary>
        public int SchoolCategoryDescriptorId { get; set; } // SchoolCategoryDescriptorId (Primary key)

        ///<summary>
        /// The identifier assigned to a school.
        ///</summary>
        public int SchoolId { get; set; } // SchoolId (Primary key)
        public System.DateTime CreateDate { get; set; } // CreateDate

        // Foreign keys

        /// <summary>
        /// Parent School pointed by [SchoolCategory].([SchoolId]) (FK_SchoolCategory_School)
        /// </summary>
        public School School { get; set; } // FK_SchoolCategory_School

        /// <summary>
        /// Parent SchoolCategoryDescriptor pointed by [SchoolCategory].([SchoolCategoryDescriptorId]) (FK_SchoolCategory_SchoolCategoryDescriptor)
        /// </summary>
        public SchoolCategoryDescriptor SchoolCategoryDescriptor { get; set; } // FK_SchoolCategory_SchoolCategoryDescriptor

        public SchoolCategory()
        {
            CreateDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
