// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // SchoolGradeLevel
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class SchoolGradeLevelConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SchoolGradeLevel>
    {
        public SchoolGradeLevelConfiguration()
            : this("edfi")
        {
        }

        public SchoolGradeLevelConfiguration(string schema)
        {
            ToTable("SchoolGradeLevel", schema);
            HasKey(x => new { x.GradeLevelDescriptorId, x.SchoolId });

            Property(x => x.GradeLevelDescriptorId).HasColumnName(@"GradeLevelDescriptorId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SchoolId).HasColumnName(@"SchoolId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime2").IsRequired();

            // Foreign keys
            HasRequired(a => a.GradeLevelDescriptor).WithMany(b => b.SchoolGradeLevels).HasForeignKey(c => c.GradeLevelDescriptorId).WillCascadeOnDelete(false); // FK_SchoolGradeLevel_GradeLevelDescriptor
            HasRequired(a => a.School).WithMany(b => b.SchoolGradeLevels).HasForeignKey(c => c.SchoolId); // FK_SchoolGradeLevel_School
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
