// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // School
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class SchoolConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<School>
    {
        public SchoolConfiguration()
            : this("edfi")
        {
        }

        public SchoolConfiguration(string schema)
        {
            ToTable("School", schema);
            HasKey(x => x.SchoolId);

            Property(x => x.SchoolId).HasColumnName(@"SchoolId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SchoolTypeDescriptorId).HasColumnName(@"SchoolTypeDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.CharterStatusDescriptorId).HasColumnName(@"CharterStatusDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.TitleIPartASchoolDesignationDescriptorId).HasColumnName(@"TitleIPartASchoolDesignationDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.MagnetSpecialProgramEmphasisSchoolDescriptorId).HasColumnName(@"MagnetSpecialProgramEmphasisSchoolDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.AdministrativeFundingControlDescriptorId).HasColumnName(@"AdministrativeFundingControlDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.InternetAccessDescriptorId).HasColumnName(@"InternetAccessDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.LocalEducationAgencyId).HasColumnName(@"LocalEducationAgencyId").HasColumnType("int").IsOptional();
            Property(x => x.CharterApprovalAgencyTypeDescriptorId).HasColumnName(@"CharterApprovalAgencyTypeDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.CharterApprovalSchoolYear).HasColumnName(@"CharterApprovalSchoolYear").HasColumnType("smallint").IsOptional();

            // Foreign keys
            HasOptional(a => a.LocalEducationAgency).WithMany(b => b.Schools).HasForeignKey(c => c.LocalEducationAgencyId).WillCascadeOnDelete(false); // FK_School_LocalEducationAgency
            HasRequired(a => a.EducationOrganization).WithOptional(b => b.School); // FK_School_EducationOrganization
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
