// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // School
    ///<summary>
    /// This entity represents an educational organization that includes staff and students who participate in classes and educational activity groups.
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class School
    {

        ///<summary>
        /// The identifier assigned to a school.
        ///</summary>
        public int SchoolId { get; set; } // SchoolId (Primary key)

        ///<summary>
        /// The type of education institution as classified by its primary focus.
        ///</summary>
        public int? SchoolTypeDescriptorId { get; set; } // SchoolTypeDescriptorId

        ///<summary>
        /// A school or agency providing free public elementary or secondary education to eligible students under a specific charter granted by the state legislature or other appropriate authority and designated by such authority to be a charter school.
        ///</summary>
        public int? CharterStatusDescriptorId { get; set; } // CharterStatusDescriptorId

        ///<summary>
        /// Denotes the Title I Part A designation for the school.
        ///</summary>
        public int? TitleIPartASchoolDesignationDescriptorId { get; set; } // TitleIPartASchoolDesignationDescriptorId

        ///<summary>
        /// A school that has been designed: 1) to attract students of different racial/ethnic backgrounds for the purpose of reducing, preventing, or eliminating racial isolation; and/or 2) to provide an academic or social focus on a particular theme (e.g., science/math, performing arts, gifted/talented, or foreign language).
        ///</summary>
        public int? MagnetSpecialProgramEmphasisSchoolDescriptorId { get; set; } // MagnetSpecialProgramEmphasisSchoolDescriptorId

        ///<summary>
        /// The type of education institution as classified by its funding source, for example public or private.
        ///</summary>
        public int? AdministrativeFundingControlDescriptorId { get; set; } // AdministrativeFundingControlDescriptorId

        ///<summary>
        /// The type of Internet access available.
        ///</summary>
        public int? InternetAccessDescriptorId { get; set; } // InternetAccessDescriptorId

        ///<summary>
        /// The identifier assigned to a local education agency.
        ///</summary>
        public int? LocalEducationAgencyId { get; set; } // LocalEducationAgencyId

        ///<summary>
        /// The type of agency that approved the establishment or continuation of a charter school.
        ///</summary>
        public int? CharterApprovalAgencyTypeDescriptorId { get; set; } // CharterApprovalAgencyTypeDescriptorId

        ///<summary>
        /// The school year in which a charter school was initially approved.
        ///</summary>
        public short? CharterApprovalSchoolYear { get; set; } // CharterApprovalSchoolYear

        // Reverse navigation

        /// <summary>
        /// Child CourseOfferings where [CourseOffering].[SchoolId] point to this entity (FK_CourseOffering_School)
        /// </summary>
        public System.Collections.Generic.ICollection<CourseOffering> CourseOfferings { get; set; } // CourseOffering.FK_CourseOffering_School
        /// <summary>
        /// Child Locations where [Location].[SchoolId] point to this entity (FK_Location_School)
        /// </summary>
        public System.Collections.Generic.ICollection<Location> Locations { get; set; } // Location.FK_Location_School
        /// <summary>
        /// Child SchoolCategories where [SchoolCategory].[SchoolId] point to this entity (FK_SchoolCategory_School)
        /// </summary>
        public System.Collections.Generic.ICollection<SchoolCategory> SchoolCategories { get; set; } // SchoolCategory.FK_SchoolCategory_School
        /// <summary>
        /// Child SchoolGradeLevels where [SchoolGradeLevel].[SchoolId] point to this entity (FK_SchoolGradeLevel_School)
        /// </summary>
        public System.Collections.Generic.ICollection<SchoolGradeLevel> SchoolGradeLevels { get; set; } // SchoolGradeLevel.FK_SchoolGradeLevel_School
        /// <summary>
        /// Child Sections where [Section].[LocationSchoolId] point to this entity (FK_Section_School)
        /// </summary>
        public System.Collections.Generic.ICollection<Section> Sections { get; set; } // Section.FK_Section_School
        /// <summary>
        /// Child Sessions where [Session].[SchoolId] point to this entity (FK_Session_School)
        /// </summary>
        public System.Collections.Generic.ICollection<Session> Sessions { get; set; } // Session.FK_Session_School
        /// <summary>
        /// Child StudentSchoolAssociations where [StudentSchoolAssociation].[SchoolId] point to this entity (FK_StudentSchoolAssociation_School)
        /// </summary>
        public System.Collections.Generic.ICollection<StudentSchoolAssociation> StudentSchoolAssociations { get; set; } // StudentSchoolAssociation.FK_StudentSchoolAssociation_School

        // Foreign keys

        /// <summary>
        /// Parent EducationOrganization pointed by [School].([SchoolId]) (FK_School_EducationOrganization)
        /// </summary>
        public EducationOrganization EducationOrganization { get; set; } // FK_School_EducationOrganization

        /// <summary>
        /// Parent LocalEducationAgency pointed by [School].([LocalEducationAgencyId]) (FK_School_LocalEducationAgency)
        /// </summary>
        public LocalEducationAgency LocalEducationAgency { get; set; } // FK_School_LocalEducationAgency

        public School()
        {
            CourseOfferings = new System.Collections.Generic.List<CourseOffering>();
            Locations = new System.Collections.Generic.List<Location>();
            SchoolCategories = new System.Collections.Generic.List<SchoolCategory>();
            SchoolGradeLevels = new System.Collections.Generic.List<SchoolGradeLevel>();
            Sections = new System.Collections.Generic.List<Section>();
            Sessions = new System.Collections.Generic.List<Session>();
            StudentSchoolAssociations = new System.Collections.Generic.List<StudentSchoolAssociation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
