// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // SchoolCategory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class SchoolCategoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SchoolCategory>
    {
        public SchoolCategoryConfiguration()
            : this("edfi")
        {
        }

        public SchoolCategoryConfiguration(string schema)
        {
            ToTable("SchoolCategory", schema);
            HasKey(x => new { x.SchoolCategoryDescriptorId, x.SchoolId });

            Property(x => x.SchoolCategoryDescriptorId).HasColumnName(@"SchoolCategoryDescriptorId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SchoolId).HasColumnName(@"SchoolId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime2").IsRequired();

            // Foreign keys
            HasRequired(a => a.School).WithMany(b => b.SchoolCategories).HasForeignKey(c => c.SchoolId); // FK_SchoolCategory_School
            HasRequired(a => a.SchoolCategoryDescriptor).WithMany(b => b.SchoolCategories).HasForeignKey(c => c.SchoolCategoryDescriptorId).WillCascadeOnDelete(false); // FK_SchoolCategory_SchoolCategoryDescriptor
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
