// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // Section
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class SectionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Section>
    {
        public SectionConfiguration()
            : this("edfi")
        {
        }

        public SectionConfiguration(string schema)
        {
            ToTable("Section", schema);
            HasKey(x => new { x.LocalCourseCode, x.SchoolId, x.SchoolYear, x.SectionIdentifier, x.SessionName });

            Property(x => x.LocalCourseCode).HasColumnName(@"LocalCourseCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(60).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SchoolId).HasColumnName(@"SchoolId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SchoolYear).HasColumnName(@"SchoolYear").HasColumnType("smallint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SectionIdentifier).HasColumnName(@"SectionIdentifier").HasColumnType("nvarchar").IsRequired().HasMaxLength(255).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SessionName).HasColumnName(@"SessionName").HasColumnType("nvarchar").IsRequired().HasMaxLength(60).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SequenceOfCourse).HasColumnName(@"SequenceOfCourse").HasColumnType("int").IsOptional();
            Property(x => x.EducationalEnvironmentDescriptorId).HasColumnName(@"EducationalEnvironmentDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.MediumOfInstructionDescriptorId).HasColumnName(@"MediumOfInstructionDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.PopulationServedDescriptorId).HasColumnName(@"PopulationServedDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.AvailableCredits).HasColumnName(@"AvailableCredits").HasColumnType("decimal").IsOptional().HasPrecision(9,3);
            Property(x => x.AvailableCreditTypeDescriptorId).HasColumnName(@"AvailableCreditTypeDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.AvailableCreditConversion).HasColumnName(@"AvailableCreditConversion").HasColumnType("decimal").IsOptional().HasPrecision(9,2);
            Property(x => x.InstructionLanguageDescriptorId).HasColumnName(@"InstructionLanguageDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.LocationSchoolId).HasColumnName(@"LocationSchoolId").HasColumnType("int").IsOptional();
            Property(x => x.LocationClassroomIdentificationCode).HasColumnName(@"LocationClassroomIdentificationCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(60);
            Property(x => x.OfficialAttendancePeriod).HasColumnName(@"OfficialAttendancePeriod").HasColumnType("bit").IsOptional();
            Property(x => x.SectionName).HasColumnName(@"SectionName").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Discriminator).HasColumnName(@"Discriminator").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.LastModifiedDate).HasColumnName(@"LastModifiedDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.ChangeVersion).HasColumnName(@"ChangeVersion").HasColumnType("bigint").IsRequired();

            // Foreign keys
            HasOptional(a => a.Location).WithMany(b => b.Sections).HasForeignKey(c => new { c.LocationClassroomIdentificationCode, c.LocationSchoolId }).WillCascadeOnDelete(false); // FK_Section_Location
            HasOptional(a => a.School).WithMany(b => b.Sections).HasForeignKey(c => c.LocationSchoolId).WillCascadeOnDelete(false); // FK_Section_School
            HasRequired(a => a.CourseOffering).WithMany(b => b.Sections).HasForeignKey(c => new { c.LocalCourseCode, c.SchoolId, c.SchoolYear, c.SessionName }).WillCascadeOnDelete(false); // FK_Section_CourseOffering
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
