// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // Session
    ///<summary>
    /// A term in the school year, generally a unit of time into which courses are scheduled, instruction occurs and by which credits are awarded. Sessions may be interrupted by vacations or other events.
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class Session
    {

        ///<summary>
        /// The identifier assigned to a school.
        ///</summary>
        public int SchoolId { get; set; } // SchoolId (Primary key)

        ///<summary>
        /// The identifier for the school year.
        ///</summary>
        public short SchoolYear { get; set; } // SchoolYear (Primary key)

        ///<summary>
        /// The identifier for the calendar for the academic session (e.g., 2010/11, 2011 Summer).
        ///</summary>
        public string SessionName { get; set; } // SessionName (Primary key) (length: 60)

        ///<summary>
        /// Month, day, and year of the first day of the Session.
        ///</summary>
        public System.DateTime BeginDate { get; set; } // BeginDate

        ///<summary>
        /// Month, day and year of the last day of the Session.
        ///</summary>
        public System.DateTime EndDate { get; set; } // EndDate

        ///<summary>
        /// An descriptor value indicating the term (e.g. &apos;Semester&apos;, &apos;Quarter&apos;, etc.).
        ///</summary>
        public int TermDescriptorId { get; set; } // TermDescriptorId

        ///<summary>
        /// The total number of instructional days in the school calendar.
        ///</summary>
        public int TotalInstructionalDays { get; set; } // TotalInstructionalDays
        public string Discriminator { get; set; } // Discriminator (length: 128)
        public System.DateTime CreateDate { get; set; } // CreateDate
        public System.DateTime LastModifiedDate { get; set; } // LastModifiedDate
        public System.Guid Id { get; set; } // Id
        public long ChangeVersion { get; set; } // ChangeVersion

        // Reverse navigation

        /// <summary>
        /// Child CourseOfferings where [CourseOffering].([SchoolId], [SchoolYear], [SessionName]) point to this entity (FK_CourseOffering_Session)
        /// </summary>
        public System.Collections.Generic.ICollection<CourseOffering> CourseOfferings { get; set; } // CourseOffering.FK_CourseOffering_Session

        // Foreign keys

        /// <summary>
        /// Parent School pointed by [Session].([SchoolId]) (FK_Session_School)
        /// </summary>
        public School School { get; set; } // FK_Session_School

        /// <summary>
        /// Parent TermDescriptor pointed by [Session].([TermDescriptorId]) (FK_Session_TermDescriptor)
        /// </summary>
        public TermDescriptor TermDescriptor { get; set; } // FK_Session_TermDescriptor

        public Session()
        {
            CreateDate = System.DateTime.Now;
            LastModifiedDate = System.DateTime.Now;
            Id = System.Guid.NewGuid();
            CourseOfferings = new System.Collections.Generic.List<CourseOffering>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
