// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // StaffElectronicMail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class StaffElectronicMailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<StaffElectronicMail>
    {
        public StaffElectronicMailConfiguration()
            : this("edfi")
        {
        }

        public StaffElectronicMailConfiguration(string schema)
        {
            ToTable("StaffElectronicMail", schema);
            HasKey(x => new { x.ElectronicMailAddress, x.ElectronicMailTypeDescriptorId, x.StaffUSI });

            Property(x => x.ElectronicMailAddress).HasColumnName(@"ElectronicMailAddress").HasColumnType("nvarchar").IsRequired().HasMaxLength(128).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ElectronicMailTypeDescriptorId).HasColumnName(@"ElectronicMailTypeDescriptorId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.StaffUSI).HasColumnName(@"StaffUSI").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.PrimaryEmailAddressIndicator).HasColumnName(@"PrimaryEmailAddressIndicator").HasColumnType("bit").IsOptional();
            Property(x => x.DoNotPublishIndicator).HasColumnName(@"DoNotPublishIndicator").HasColumnType("bit").IsOptional();
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime2").IsRequired();

            // Foreign keys
            HasRequired(a => a.ElectronicMailTypeDescriptor).WithMany(b => b.StaffElectronicMails).HasForeignKey(c => c.ElectronicMailTypeDescriptorId).WillCascadeOnDelete(false); // FK_StaffElectronicMail_ElectronicMailTypeDescriptor
            HasRequired(a => a.Staff).WithMany(b => b.StaffElectronicMails).HasForeignKey(c => c.StaffUSI); // FK_StaffElectronicMail_Staff
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
