// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // Staff
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class StaffConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Staff>
    {
        public StaffConfiguration()
            : this("edfi")
        {
        }

        public StaffConfiguration(string schema)
        {
            ToTable("Staff", schema);
            HasKey(x => x.StaffUSI);

            Property(x => x.StaffUSI).HasColumnName(@"StaffUSI").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PersonalTitlePrefix).HasColumnName(@"PersonalTitlePrefix").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar").IsRequired().HasMaxLength(75);
            Property(x => x.MiddleName).HasColumnName(@"MiddleName").HasColumnType("nvarchar").IsOptional().HasMaxLength(75);
            Property(x => x.LastSurname).HasColumnName(@"LastSurname").HasColumnType("nvarchar").IsRequired().HasMaxLength(75);
            Property(x => x.GenerationCodeSuffix).HasColumnName(@"GenerationCodeSuffix").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.MaidenName).HasColumnName(@"MaidenName").HasColumnType("nvarchar").IsOptional().HasMaxLength(75);
            Property(x => x.SexDescriptorId).HasColumnName(@"SexDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.BirthDate).HasColumnName(@"BirthDate").HasColumnType("date").IsOptional();
            Property(x => x.HispanicLatinoEthnicity).HasColumnName(@"HispanicLatinoEthnicity").HasColumnType("bit").IsOptional();
            Property(x => x.OldEthnicityDescriptorId).HasColumnName(@"OldEthnicityDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.CitizenshipStatusDescriptorId).HasColumnName(@"CitizenshipStatusDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.HighestCompletedLevelOfEducationDescriptorId).HasColumnName(@"HighestCompletedLevelOfEducationDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.YearsOfPriorProfessionalExperience).HasColumnName(@"YearsOfPriorProfessionalExperience").HasColumnType("decimal").IsOptional().HasPrecision(5,2);
            Property(x => x.YearsOfPriorTeachingExperience).HasColumnName(@"YearsOfPriorTeachingExperience").HasColumnType("decimal").IsOptional().HasPrecision(5,2);
            Property(x => x.LoginId).HasColumnName(@"LoginId").HasColumnType("nvarchar").IsOptional().HasMaxLength(60);
            Property(x => x.HighlyQualifiedTeacher).HasColumnName(@"HighlyQualifiedTeacher").HasColumnType("bit").IsOptional();
            Property(x => x.StaffUniqueId).HasColumnName(@"StaffUniqueId").HasColumnType("nvarchar").IsRequired().HasMaxLength(32);
            Property(x => x.Discriminator).HasColumnName(@"Discriminator").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.LastModifiedDate).HasColumnName(@"LastModifiedDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.ChangeVersion).HasColumnName(@"ChangeVersion").HasColumnType("bigint").IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
