// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // Staff
    ///<summary>
    /// This entity represents an individual who performs specified activities for any public or private education institution or agency that provides instructional and/or support services to students or staff at the early childhood level through high school completion. For example, this includes:
    /// 1. An &quot;employee&quot; who performs services under the direction of the employing institution or agency is compensated for such services by the employer and is eligible for employee benefits and wage or salary tax withholdings
    /// 2. A &quot;contractor&quot; or &quot;consultant&quot; who performs services for an agreed upon fee or an employee of a management service contracted to work on site
    /// 3. A &quot;volunteer&quot; who performs services on a voluntary and uncompensated basis
    /// 4. An in-kind service provider
    /// 5. An independent contractor or businessperson working at a school site.
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class Staff
    {

        ///<summary>
        /// A unique alphanumeric code assigned to a staff.
        ///</summary>
        public int StaffUSI { get; set; } // StaffUSI (Primary key)

        ///<summary>
        /// A prefix used to denote the title, degree, position, or seniority of the person.
        ///</summary>
        public string PersonalTitlePrefix { get; set; } // PersonalTitlePrefix (length: 30)

        ///<summary>
        /// A name given to an individual at birth, baptism, or during another naming ceremony, or through legal change.
        ///</summary>
        public string FirstName { get; set; } // FirstName (length: 75)

        ///<summary>
        /// A secondary name given to an individual at birth, baptism, or during another naming ceremony.
        ///</summary>
        public string MiddleName { get; set; } // MiddleName (length: 75)

        ///<summary>
        /// The name borne in common by members of a family.
        ///</summary>
        public string LastSurname { get; set; } // LastSurname (length: 75)

        ///<summary>
        /// An appendage, if any, used to denote an individual&apos;s generation in his family (e.g., Jr., Sr., III).
        ///</summary>
        public string GenerationCodeSuffix { get; set; } // GenerationCodeSuffix (length: 10)

        ///<summary>
        /// The person&apos;s maiden name.
        ///</summary>
        public string MaidenName { get; set; } // MaidenName (length: 75)

        ///<summary>
        /// A person&apos;s gender.
        ///</summary>
        public int? SexDescriptorId { get; set; } // SexDescriptorId

        ///<summary>
        /// The month, day, and year on which an individual was born.
        ///</summary>
        public System.DateTime? BirthDate { get; set; } // BirthDate

        ///<summary>
        /// An indication that the individual traces his or her origin or descent to Mexico, Puerto Rico, Cuba, Central, and South America, and other Spanish cultures, regardless of race. The term, &quot;Spanish origin,&quot; can be used in addition to &quot;Hispanic or Latino.&quot;
        ///</summary>
        public bool? HispanicLatinoEthnicity { get; set; } // HispanicLatinoEthnicity

        ///<summary>
        /// Previous definition of Ethnicity combining Hispanic/Latino and race:
        ///         1 - American Indian or Alaskan Native
        ///         2 - Asian or Pacific Islander
        ///         3 - Black, not of Hispanic origin
        ///         4 - Hispanic
        ///         5 - White, not of Hispanic origin.
        ///</summary>
        public int? OldEthnicityDescriptorId { get; set; } // OldEthnicityDescriptorId

        ///<summary>
        /// An indicator of whether or not the person is a U.S. citizen.
        ///</summary>
        public int? CitizenshipStatusDescriptorId { get; set; } // CitizenshipStatusDescriptorId

        ///<summary>
        /// The extent of formal instruction an individual has received (e.g., the highest grade in school completed or its equivalent or the highest degree received).
        ///</summary>
        public int? HighestCompletedLevelOfEducationDescriptorId { get; set; } // HighestCompletedLevelOfEducationDescriptorId

        ///<summary>
        /// The total number of years that an individual has previously held a similar professional position in one or more education institutions.
        ///</summary>
        public decimal? YearsOfPriorProfessionalExperience { get; set; } // YearsOfPriorProfessionalExperience

        ///<summary>
        /// The total number of years that an individual has previously held a teaching position in one or more education institutions.
        ///</summary>
        public decimal? YearsOfPriorTeachingExperience { get; set; } // YearsOfPriorTeachingExperience

        ///<summary>
        /// The login ID for the user; used for security access control interface.
        ///</summary>
        public string LoginId { get; set; } // LoginId (length: 60)

        ///<summary>
        /// An indication of whether a teacher is classified as highly qualified for his/her assignment according to state definition. This attribute indicates the teacher is highly qualified for ALL Sections being taught.
        ///</summary>
        public bool? HighlyQualifiedTeacher { get; set; } // HighlyQualifiedTeacher

        ///<summary>
        /// A unique alphanumeric code assigned to a staff.
        ///</summary>
        public string StaffUniqueId { get; set; } // StaffUniqueId (length: 32)
        public string Discriminator { get; set; } // Discriminator (length: 128)
        public System.DateTime CreateDate { get; set; } // CreateDate
        public System.DateTime LastModifiedDate { get; set; } // LastModifiedDate
        public System.Guid Id { get; set; } // Id
        public long ChangeVersion { get; set; } // ChangeVersion

        // Reverse navigation

        /// <summary>
        /// Child StaffElectronicMails where [StaffElectronicMail].[StaffUSI] point to this entity (FK_StaffElectronicMail_Staff)
        /// </summary>
        public System.Collections.Generic.ICollection<StaffElectronicMail> StaffElectronicMails { get; set; } // StaffElectronicMail.FK_StaffElectronicMail_Staff
        /// <summary>
        /// Child StaffSectionAssociations where [StaffSectionAssociation].[StaffUSI] point to this entity (FK_StaffSectionAssociation_Staff)
        /// </summary>
        public System.Collections.Generic.ICollection<StaffSectionAssociation> StaffSectionAssociations { get; set; } // StaffSectionAssociation.FK_StaffSectionAssociation_Staff

        public Staff()
        {
            CreateDate = System.DateTime.Now;
            LastModifiedDate = System.DateTime.Now;
            Id = System.Guid.NewGuid();
            StaffElectronicMails = new System.Collections.Generic.List<StaffElectronicMail>();
            StaffSectionAssociations = new System.Collections.Generic.List<StaffSectionAssociation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
