// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // StudentSchoolAssociationEnrollmentType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class StudentSchoolAssociationEnrollmentType
    {
        public int EnrollmentTypeDescriptorId { get; set; } // EnrollmentTypeDescriptorId (Primary key)

        ///<summary>
        /// The month, day, and year on which an individual enters and begins to receive instructional services in a school.
        ///</summary>
        public System.DateTime EntryDate { get; set; } // EntryDate (Primary key)

        ///<summary>
        /// The identifier assigned to a school.
        ///</summary>
        public int SchoolId { get; set; } // SchoolId (Primary key)

        ///<summary>
        /// A unique alphanumeric code assigned to a student.
        ///</summary>
        public int StudentUsi { get; set; } // StudentUSI (Primary key)
        public System.DateTime CreateDate { get; set; } // CreateDate

        // Foreign keys

        /// <summary>
        /// Parent StudentSchoolAssociation pointed by [StudentSchoolAssociationEnrollmentType].([EntryDate], [SchoolId], [StudentUsi]) (FK_StudentSchoolAssociationEnrollmentType_StudentSchoolAssociation)
        /// </summary>
        public StudentSchoolAssociation StudentSchoolAssociation { get; set; } // FK_StudentSchoolAssociationEnrollmentType_StudentSchoolAssociation

        public StudentSchoolAssociationEnrollmentType()
        {
            CreateDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
