// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // StudentSchoolAssociationEnrollmentType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class StudentSchoolAssociationEnrollmentTypeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<StudentSchoolAssociationEnrollmentType>
    {
        public StudentSchoolAssociationEnrollmentTypeConfiguration()
            : this("wi")
        {
        }

        public StudentSchoolAssociationEnrollmentTypeConfiguration(string schema)
        {
            ToTable("StudentSchoolAssociationEnrollmentType", schema);
            HasKey(x => new { x.EnrollmentTypeDescriptorId, x.EntryDate, x.SchoolId, x.StudentUsi });

            Property(x => x.EnrollmentTypeDescriptorId).HasColumnName(@"EnrollmentTypeDescriptorId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.EntryDate).HasColumnName(@"EntryDate").HasColumnType("date").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SchoolId).HasColumnName(@"SchoolId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.StudentUsi).HasColumnName(@"StudentUSI").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime2").IsRequired();

            // Foreign keys
            HasRequired(a => a.StudentSchoolAssociation).WithMany(b => b.StudentSchoolAssociationEnrollmentTypes).HasForeignKey(c => new { c.EntryDate, c.SchoolId, c.StudentUsi }); // FK_StudentSchoolAssociationEnrollmentType_StudentSchoolAssociation
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
