// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // StudentEducationOrganizationAssociation
    ///<summary>
    /// This association represents student information as reported in the context of the student&apos;s relationship to the Education Organization. Enrollment relationship semantics are covered by StudentSchoolAssociation.
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class StudentEducationOrganizationAssociation
    {

        ///<summary>
        /// The identifier assigned to an education organization.
        ///</summary>
        public int EducationOrganizationId { get; set; } // EducationOrganizationId (Primary key)

        ///<summary>
        /// A unique alphanumeric code assigned to a student.
        ///</summary>
        public int StudentUsi { get; set; } // StudentUSI (Primary key)

        ///<summary>
        /// The student&apos;s gender as last reported to the education organization.
        ///</summary>
        public int SexDescriptorId { get; set; } // SexDescriptorId

        ///<summary>
        /// Locator reference for the student photo. The specification for that reference is left to local definition.
        ///</summary>
        public string ProfileThumbnail { get; set; } // ProfileThumbnail (length: 255)

        ///<summary>
        /// An indication that the individual traces his or her origin or descent to Mexico, Puerto Rico, Cuba, Central, and South America, and other Spanish cultures, regardless of race, as last reported to the education organization. The term, &quot;Spanish origin,&quot; can be used in addition to &quot;Hispanic or Latino.&quot;
        ///</summary>
        public bool? HispanicLatinoEthnicity { get; set; } // HispanicLatinoEthnicity

        ///<summary>
        /// Previous definition of Ethnicity combining Hispanic/Latino and race:
        ///         1 - American Indian or Alaskan Native
        ///         2 - Asian or Pacific Islander
        ///         3 - Black, not of Hispanic origin
        ///         4 - Hispanic
        ///         5 - White, not of Hispanic origin.
        ///</summary>
        public int? OldEthnicityDescriptorId { get; set; } // OldEthnicityDescriptorId

        ///<summary>
        /// An indication that the student has been identified as limited English proficient by the Language Proficiency Assessment Committee (LPAC), or English proficient.
        ///</summary>
        public int? LimitedEnglishProficiencyDescriptorId { get; set; } // LimitedEnglishProficiencyDescriptorId

        ///<summary>
        /// The login ID for the user; used for security access control interface.
        ///</summary>
        public string LoginId { get; set; } // LoginId (length: 60)
        public string Discriminator { get; set; } // Discriminator (length: 128)
        public System.DateTime CreateDate { get; set; } // CreateDate
        public System.DateTime LastModifiedDate { get; set; } // LastModifiedDate
        public System.Guid Id { get; set; } // Id
        public long ChangeVersion { get; set; } // ChangeVersion

        // Reverse navigation

        /// <summary>
        /// Child StudentEducationOrganizationAssociationElectronicMails where [StudentEducationOrganizationAssociationElectronicMail].([EducationOrganizationId], [StudentUSI]) point to this entity (FK_StudentEducationOrganizationAssociationElectronicMail_StudentEducationOrganizationAssociation)
        /// </summary>
        public System.Collections.Generic.ICollection<StudentEducationOrganizationAssociationElectronicMail> StudentEducationOrganizationAssociationElectronicMails { get; set; } // StudentEducationOrganizationAssociationElectronicMail.FK_StudentEducationOrganizationAssociationElectronicMail_StudentEducationOrganizationAssociation

        // Foreign keys

        /// <summary>
        /// Parent EducationOrganization pointed by [StudentEducationOrganizationAssociation].([EducationOrganizationId]) (FK_StudentEducationOrganizationAssociation_EducationOrganization)
        /// </summary>
        public EducationOrganization EducationOrganization { get; set; } // FK_StudentEducationOrganizationAssociation_EducationOrganization

        /// <summary>
        /// Parent Student pointed by [StudentEducationOrganizationAssociation].([StudentUsi]) (FK_StudentEducationOrganizationAssociation_Student)
        /// </summary>
        public Student Student { get; set; } // FK_StudentEducationOrganizationAssociation_Student

        public StudentEducationOrganizationAssociation()
        {
            CreateDate = System.DateTime.Now;
            LastModifiedDate = System.DateTime.Now;
            Id = System.Guid.NewGuid();
            StudentEducationOrganizationAssociationElectronicMails = new System.Collections.Generic.List<StudentEducationOrganizationAssociationElectronicMail>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
