// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // StudentEducationOrganizationAssociationElectronicMail
    ///<summary>
    /// The numbers, letters, and symbols used to identify an electronic mail (e-mail) user within the network to which the individual or organization belongs.
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class StudentEducationOrganizationAssociationElectronicMail
    {

        ///<summary>
        /// The identifier assigned to an education organization.
        ///</summary>
        public int EducationOrganizationId { get; set; } // EducationOrganizationId (Primary key)

        ///<summary>
        /// The electronic mail (e-mail) address listed for an individual or organization.
        ///</summary>
        public string ElectronicMailAddress { get; set; } // ElectronicMailAddress (Primary key) (length: 128)

        ///<summary>
        /// The type of email listed for an individual or organization. For example: Home/Personal, Work, etc.)
        ///</summary>
        public int ElectronicMailTypeDescriptorId { get; set; } // ElectronicMailTypeDescriptorId (Primary key)

        ///<summary>
        /// A unique alphanumeric code assigned to a student.
        ///</summary>
        public int StudentUsi { get; set; } // StudentUSI (Primary key)

        ///<summary>
        /// An indication that the electronic mail address should be used as the principal electronic mail address for an individual or organization.
        ///</summary>
        public bool? PrimaryEmailAddressIndicator { get; set; } // PrimaryEmailAddressIndicator

        ///<summary>
        /// An indication that the electronic email address should not be published.
        ///</summary>
        public bool? DoNotPublishIndicator { get; set; } // DoNotPublishIndicator
        public System.DateTime CreateDate { get; set; } // CreateDate

        // Foreign keys

        /// <summary>
        /// Parent ElectronicMailTypeDescriptor pointed by [StudentEducationOrganizationAssociationElectronicMail].([ElectronicMailTypeDescriptorId]) (FK_StudentEducationOrganizationAssociationElectronicMail_ElectronicMailTypeDescriptor)
        /// </summary>
        public ElectronicMailTypeDescriptor ElectronicMailTypeDescriptor { get; set; } // FK_StudentEducationOrganizationAssociationElectronicMail_ElectronicMailTypeDescriptor

        /// <summary>
        /// Parent StudentEducationOrganizationAssociation pointed by [StudentEducationOrganizationAssociationElectronicMail].([EducationOrganizationId], [StudentUsi]) (FK_StudentEducationOrganizationAssociationElectronicMail_StudentEducationOrganizationAssociation)
        /// </summary>
        public StudentEducationOrganizationAssociation StudentEducationOrganizationAssociation { get; set; } // FK_StudentEducationOrganizationAssociationElectronicMail_StudentEducationOrganizationAssociation

        public StudentEducationOrganizationAssociationElectronicMail()
        {
            CreateDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
