// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // Student
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class StudentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Student>
    {
        public StudentConfiguration()
            : this("edfi")
        {
        }

        public StudentConfiguration(string schema)
        {
            ToTable("Student", schema);
            HasKey(x => x.StudentUsi);

            Property(x => x.StudentUsi).HasColumnName(@"StudentUSI").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PersonalTitlePrefix).HasColumnName(@"PersonalTitlePrefix").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar").IsRequired().HasMaxLength(75);
            Property(x => x.MiddleName).HasColumnName(@"MiddleName").HasColumnType("nvarchar").IsOptional().HasMaxLength(75);
            Property(x => x.LastSurname).HasColumnName(@"LastSurname").HasColumnType("nvarchar").IsRequired().HasMaxLength(75);
            Property(x => x.GenerationCodeSuffix).HasColumnName(@"GenerationCodeSuffix").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.MaidenName).HasColumnName(@"MaidenName").HasColumnType("nvarchar").IsOptional().HasMaxLength(75);
            Property(x => x.BirthDate).HasColumnName(@"BirthDate").HasColumnType("date").IsRequired();
            Property(x => x.BirthCity).HasColumnName(@"BirthCity").HasColumnType("nvarchar").IsOptional().HasMaxLength(30);
            Property(x => x.BirthStateAbbreviationDescriptorId).HasColumnName(@"BirthStateAbbreviationDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.BirthInternationalProvince).HasColumnName(@"BirthInternationalProvince").HasColumnType("nvarchar").IsOptional().HasMaxLength(150);
            Property(x => x.BirthCountryDescriptorId).HasColumnName(@"BirthCountryDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.DateEnteredUS).HasColumnName(@"DateEnteredUS").HasColumnType("date").IsOptional();
            Property(x => x.MultipleBirthStatus).HasColumnName(@"MultipleBirthStatus").HasColumnType("bit").IsOptional();
            Property(x => x.BirthSexDescriptorId).HasColumnName(@"BirthSexDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.CitizenshipStatusDescriptorId).HasColumnName(@"CitizenshipStatusDescriptorId").HasColumnType("int").IsOptional();
            Property(x => x.StudentUniqueId).HasColumnName(@"StudentUniqueId").HasColumnType("nvarchar").IsRequired().HasMaxLength(32);
            Property(x => x.Discriminator).HasColumnName(@"Discriminator").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.LastModifiedDate).HasColumnName(@"LastModifiedDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.ChangeVersion).HasColumnName(@"ChangeVersion").HasColumnType("bigint").IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
