// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Api
{

    // TermDescriptor
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class TermDescriptorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TermDescriptor>
    {
        public TermDescriptorConfiguration()
            : this("edfi")
        {
        }

        public TermDescriptorConfiguration(string schema)
        {
            ToTable("TermDescriptor", schema);
            HasKey(x => x.TermDescriptorId);

            Property(x => x.TermDescriptorId).HasColumnName(@"TermDescriptorId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Descriptor).WithOptional(b => b.TermDescriptor); // FK_TermDescriptor_Descriptor
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
