// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Models
{

    // GcCourseUser
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class GcCourseUser
    {
        public int EducationOrganizationId { get; set; } // EducationOrganizationId (Primary key)
        public short SchoolYear { get; set; } // SchoolYear (Primary key)
        public int SchoolId { get; set; } // SchoolId (Primary key)
        public string LocalCourseCode { get; set; } // LocalCourseCode (Primary key) (length: 60)
        public string SessionName { get; set; } // SessionName (Primary key) (length: 60)
        public string SectionIdentifier { get; set; } // SectionIdentifier (Primary key) (length: 255)
        public string EmailAddress { get; set; } // EmailAddress (Primary key) (length: 128)
        public bool IsTeacher { get; set; } // IsTeacher
        public string UserId { get; set; } // UserId (length: 200)

        // Foreign keys

        /// <summary>
        /// Parent GcCourse pointed by [GcCourseUser].([EducationOrganizationId], [SchoolYear], [SchoolId], [LocalCourseCode], [SectionIdentifier], [SessionName]) (FK_GcCourse_GcCourseUser)
        /// </summary>
        public GcCourse GcCourse { get; set; } // FK_GcCourse_GcCourseUser

        public GcCourseUser()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
