// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Models
{

    // GcCourse
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class GcCourseConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<GcCourse>
    {
        public GcCourseConfiguration()
            : this("dbo")
        {
        }

        public GcCourseConfiguration(string schema)
        {
            ToTable("GcCourse", schema);
            HasKey(x => new { x.EducationOrganizationId, x.SchoolYear, x.SchoolId, x.LocalCourseCode, x.SectionIdentifier, x.SessionName });

            Property(x => x.EducationOrganizationId).HasColumnName(@"EducationOrganizationId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SchoolYear).HasColumnName(@"SchoolYear").HasColumnType("smallint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SchoolId).HasColumnName(@"SchoolId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.LocalCourseCode).HasColumnName(@"LocalCourseCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(60).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SessionName).HasColumnName(@"SessionName").HasColumnType("nvarchar").IsRequired().HasMaxLength(60).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SectionIdentifier).HasColumnName(@"SectionIdentifier").HasColumnType("nvarchar").IsRequired().HasMaxLength(255).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.LocalCourseTitle).HasColumnName(@"LocalCourseTitle").HasColumnType("nvarchar").IsOptional().HasMaxLength(60);
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsRequired();
            Property(x => x.GcName).HasColumnName(@"GcName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(154).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed);
            Property(x => x.Owner).HasColumnName(@"Owner").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.GcId).HasColumnName(@"GcId").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.Saved).HasColumnName(@"Saved").HasColumnType("bit").IsOptional();
            Property(x => x.Activated).HasColumnName(@"Activated").HasColumnType("bit").IsOptional();
            Property(x => x.GcMessage).HasColumnName(@"GcMessage").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
