// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Models
{

    // ProvisioningRules
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class ProvisioningRule
    {
        public int RuleId { get; set; } // RuleId (Primary key)
        public int EducationOrganizationId { get; set; } // EducationOrganizationId
        public short SchoolYear { get; set; } // SchoolYear
        public int TypeId { get; set; } // TypeId
        public int? SchoolCategoryTypeId { get; set; } // SchoolCategoryTypeId
        public string SessionName { get; set; } // SessionName (length: 60)
        public int? StaffUSI { get; set; } // StaffUSI
        public bool? IncludeExclude { get; set; } // IncludeExclude
        public bool StaffOnly { get; set; } // StaffOnly
        public bool? GroupByTitle { get; set; } // GroupByTitle
        public System.DateTime CreateDate { get; set; } // CreateDate

        // Reverse navigation

        /// <summary>
        /// Child RosterGradeLevels where [RosterGradeLevel].[RuleId] point to this entity (FK_RosterGradeLevel_ProvisioningRules)
        /// </summary>
        public System.Collections.Generic.ICollection<RosterGradeLevel> RosterGradeLevels { get; set; } // RosterGradeLevel.FK_RosterGradeLevel_ProvisioningRules
        /// <summary>
        /// Child RosterLocalCourses where [RosterLocalCourse].[RuleId] point to this entity (FK_RosterLocalCourse_ProvisioningRules)
        /// </summary>
        public System.Collections.Generic.ICollection<RosterLocalCourse> RosterLocalCourses { get; set; } // RosterLocalCourse.FK_RosterLocalCourse_ProvisioningRules
        /// <summary>
        /// Child RosterSchools where [RosterSchool].[RuleId] point to this entity (FK_RosterSchool_ProvisioningRules)
        /// </summary>
        public System.Collections.Generic.ICollection<RosterSchool> RosterSchools { get; set; } // RosterSchool.FK_RosterSchool_ProvisioningRules

        public ProvisioningRule()
        {
            TypeId = 1;
            CreateDate = System.DateTime.Now;
            RosterGradeLevels = new System.Collections.Generic.List<RosterGradeLevel>();
            RosterLocalCourses = new System.Collections.Generic.List<RosterLocalCourse>();
            RosterSchools = new System.Collections.Generic.List<RosterSchool>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
