// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Models
{

    // ProvisioningRules
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class ProvisioningRuleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ProvisioningRule>
    {
        public ProvisioningRuleConfiguration()
            : this("dbo")
        {
        }

        public ProvisioningRuleConfiguration(string schema)
        {
            ToTable("ProvisioningRules", schema);
            HasKey(x => x.RuleId);

            Property(x => x.RuleId).HasColumnName(@"RuleId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.EducationOrganizationId).HasColumnName(@"EducationOrganizationId").HasColumnType("int").IsRequired();
            Property(x => x.SchoolYear).HasColumnName(@"SchoolYear").HasColumnType("smallint").IsRequired();
            Property(x => x.TypeId).HasColumnName(@"TypeId").HasColumnType("int").IsRequired();
            Property(x => x.SchoolCategoryTypeId).HasColumnName(@"SchoolCategoryTypeId").HasColumnType("int").IsOptional();
            Property(x => x.SessionName).HasColumnName(@"SessionName").HasColumnType("nvarchar").IsOptional().HasMaxLength(60);
            Property(x => x.StaffUSI).HasColumnName(@"StaffUSI").HasColumnType("int").IsOptional();
            Property(x => x.IncludeExclude).HasColumnName(@"IncludeExclude").HasColumnType("bit").IsOptional();
            Property(x => x.StaffOnly).HasColumnName(@"StaffOnly").HasColumnType("bit").IsRequired();
            Property(x => x.GroupByTitle).HasColumnName(@"GroupByTitle").HasColumnType("bit").IsOptional();
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
