// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Models
{

    // RosterLocalCourse
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class RosterLocalCourse
    {
        public int RuleId { get; set; } // RuleId (Primary key)
        public string LocalCourseCode { get; set; } // LocalCourseCode (Primary key) (length: 60)

        // Foreign keys

        /// <summary>
        /// Parent ProvisioningRule pointed by [RosterLocalCourse].([RuleId]) (FK_RosterLocalCourse_ProvisioningRules)
        /// </summary>
        public ProvisioningRule ProvisioningRule { get; set; } // FK_RosterLocalCourse_ProvisioningRules

        public RosterLocalCourse()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
