// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Models
{

    // RosterSchool
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class RosterSchool
    {
        public int RuleId { get; set; } // RuleId (Primary key)
        public int SchoolId { get; set; } // SchoolId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent ProvisioningRule pointed by [RosterSchool].([RuleId]) (FK_RosterSchool_ProvisioningRules)
        /// </summary>
        public ProvisioningRule ProvisioningRule { get; set; } // FK_RosterSchool_ProvisioningRules

        public RosterSchool()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
