// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.8
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace WISEroster.Domain.Models
{

    // SecureItems
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.5.0")]
    public partial class SecureItemConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SecureItem>
    {
        public SecureItemConfiguration()
            : this("sec")
        {
        }

        public SecureItemConfiguration(string schema)
        {
            ToTable("SecureItems", schema);
            HasKey(x => x.ItemKey);

            Property(x => x.ItemKey).HasColumnName(@"ItemKey").HasColumnType("nvarchar").IsRequired().HasMaxLength(100).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ItemValue).HasColumnName(@"ItemValue").HasColumnType("varbinary").IsOptional().HasMaxLength(2048);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
